hash-format = "sha256"

[[files]]
file = "mods/ResourcePackUpdater-1.20.4-2.3.0.jar"
hash = "4b87e15985af5cfaedbe9543b8521a6a36b2646c1601e8345259667c26a03fe2"

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "f16a5795a6ba42c12667f25f67ad0d50f2e384a13e1378d68f2daf6464f65293"
metafile = true

[[files]]
file = "mods/blossomwarps.pw.toml"
hash = "d011dd222ff900c9bd1eea73a45665e350c6736027f7a16a5d78a65b96629614"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "9e0f5b76c982dedd73c218eca72c5e45a2d933f2c28e6dc9a7b6de4ff91de505"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "b499c0f69d4078ebfaa7755db796e3667e536cce8bff0e7290bc4071e6f14905"
metafile = true

[[files]]
file = "mods/dynamic-sound-filters.pw.toml"
hash = "51ded2ccce83cd66bd7f12b1316e492dda5f3f94e9bd89c56bd1ef113fb107bc"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8435fe34f180c963234295c6bf8de293b3450d74f2ab74389ac9bdf198d84612"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/filters-api.pw.toml"
hash = "b9480e9b507930881bda195d5ddebe107084261e5afcd1ab61cc107bef116c61"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "9dc337ffb127f1b1f24c57f8c3fc739e21b2139050d41baf55357fad8b42c83b"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "67460b0aef1e7773cfbd23e56792176512a3a79c3aa4dd8e544382d2ed06aa2e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d9d01681616a8bdb45bbdd0a053b87153bbb77a5ef997325be0b3dc10b7f8979"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "db812a9b3a4a8ea011eedc44bdc4df13a1f3cfb67130fe57d3990342566d03a8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "96cafb1b451ce577f0a74045704c2f51c3ab34d63fbba81df669c21646d33bff"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "e83c87c3d885936e666e41d8f41d97383cc0cb954ded4f6d689697f500b65a2b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "57fc1c61ba53059ccb27647cf44d4b8671ccf284fcd869ec1b6c04a94eb8335e"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "4d1a390f5dccdb9347b35f1ea854b53beecb9791368b217e8e16fa1dff32b2f9"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "07114208e332aa5fbc3e7144c2bac58ea74e50d4eaeac2b6c6cc5c41286bb335"
metafile = true

[[files]]
file = "mods/mtr-london-underground-trains.pw.toml"
hash = "6872d8df0f45517b1e2f627552d25e4cdfe568f24625141396e56a75f183f3e4"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "56365fcf55b2679a8f2ceefe5c3f949854d13945963a421d178145d0551b2fac"
metafile = true

[[files]]
file = "mods/nowheel.pw.toml"
hash = "4bc90767bb9d464408593916bcf4d9c8e7d514d260791b2fb84f24c388d4109f"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "d5311528fd2858d1c6c95f207ee65fcded1b0db497ad995743b64b9e1244b174"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "de46918876de129bf08aa27420ec9b99b373dbccac7acaebd82e46b4c28836b5"
metafile = true

[[files]]
file = "mods/russian-metro-addon.pw.toml"
hash = "73a9839e338fbfb4d8b63eb3a274daf8557fab45932085b371dec3ce8cbf5577"
metafile = true

[[files]]
file = "mods/slideshow-fabric.pw.toml"
hash = "e94c10cc685e2b6de37dc41f133918cb3a6ea1a1a72e782f2b4cffd0fc0a82a4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "521c8241593053f877a89ce447c64392c3619e16c2001b3cac7d72cbde8392d0"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c6a5c6afaf276bde5c35adb34e21155112b7defd08b83d95a81e435bc6530c42"
metafile = true

[[files]]
file = "mods/squaremap.pw.toml"
hash = "10e03effaac4de370986837d6cb0497e7c847b12bef858dbfddc4396c6cf21ff"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "75e3fb7d66b8e29bfc31b39e123c62c67fcb11d4614f2c6ac16df18a1b5e3eaf"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "d0aa439438069d14311f23a19678e28fc8763b0e8aa9f6fc5b3cdc68556d6f0d"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "b8f43a50939082d1d771497405b8c69a9a4a7fd8b32fa8828bafb723e4eb5e21"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/the-tube.pw.toml"
hash = "370562c6b363aeb7b7b35bd44b5ff7ad49560e75cb66d38c8889c84274471b95"
metafile = true

[[files]]
file = "mods/tianjin-metro.pw.toml"
hash = "01766147ff9b9877712d1a5ac3c8245282c41d3cc510567d3a57a525360c75a1"
metafile = true

[[files]]
file = "mods/time-wind.pw.toml"
hash = "f3e66d1488a2b3b90ec316c711de2f7a11162b8e814b5e1d91f54d4365313973"
metafile = true

[[files]]
file = "mods/u-team-core.pw.toml"
hash = "aa9288d48e732cb185a309cf7568919691e38e745e323d964e103495095e02fc"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "8b8ac972787f43f212193686d9c304277a54072f8a84731d5d699fb45271209c"
metafile = true

[[files]]
file = "mods/visiblebarriers.pw.toml"
hash = "51b517d73128d7d07585b4a684ae3e4cf40d6232b1c1d1fd6640eecb86b43280"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "bfcf968cabbcc7b44c61374e487f4f6832ac105699719673e4dce47a12bd3b7e"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "f2d6b24ea4a6982f876c5151f6d8640f14746db8f94470cd90add9556ebaccd3"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6c37942d0e07a8618bcd0f414ac5edff8a8beea820acaefbda7b24aa968a89bd"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "6796e2c7fabee670200cbb6d853cdf4f8938c019cc8990496d8879ac37d88523"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "b424b2e66611b4eca4a79f4d09318ee68fcbdb7b70b077a91e0e5682accec905"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "cc9f2c1cc2e516f0fc97fb6344ba020c3c627cfce5ee0242ae7e3d1bab790305"
metafile = true
