name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fcef3a364f30e9e256e686a3c7d717b8525762a0d7a3e6d6a3e3bb2d099d47f"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
