name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3b4abe796b5cd53c50ac98d43c9e199da86548d650d96503fc44e8c4e2c453e"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
