name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "416850e346fa0c803abeafe7c50b10088fe5ba9d4ea5f2070eb96d74cd1d8b11"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
