name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63a6635d47fc68507f2d3bdc3e772340d5a68650ee4dc3a322a7664ad54b8323"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
