name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02aa9a0677ee0a5c8c86bd945f26d6579a4e320b18990e1d29978d46d6e28151"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
