name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b2e7c94f4131589b4515de02aab886d50d82cf0c4f788ef4cee64152742c091"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
