name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beeb0a8f03d32400805dc18e3150379a41b6de4a62d34b0f81edd05d416daef3"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
