name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa771fa7298fc94269de721b22f8c64d50b27afe0de49165c18c1df693a29a8"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
