name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02889e928a36ebce6a9ede49d49b5374298f358e8df1b4f9c8f793360b7aa964"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
