name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fb5f7c6aed0a12e5cd9884b4a976873608225f0d376d026ab246a131f0ae241"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
