name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96fe997d158d827d3fcc4f017c9132d2bcc94cafb5f2032efe6b4609357d9de9"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
