name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77c3f6c2399cab3b264ba32b6fa8ccf276661fa34cf2009765c43c63e3ea1d19"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
