name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f44982ff946cf4c7f707bf9032c5eceec7413a1efb4e357089e52e128a4fd903"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
