name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfab23fc4c76452fa0188673889c661c7909a7371db4a1923425f3da66459709"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
