name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de02fd552edc647081ba53fb7be896e0d7cde9ec88d10a133c9ce1d350f4b136"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
