name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3779dbac70a4c4aa9372d718ffce0aafb122250c96d6cd0c5be32fbf40ad182a"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
