name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ebd43b2b39ae9a8d56dea6c95dd714fe9bbcfb2a7fe13a7926f615d37fd2bc9"

[versions]
fabric = "0.18.1"
minecraft = "1.20.4"
